ansible_user: ec2-user
ansible_password: DevOps321
CATALOGUE_HOST: catalogue-"{{ env }}.techdaws.online
MONGODB_HOST: mongodb-"{{ env }}.techdaws.online
REDIS_HOST: redis-"{{ env }}.techdaws.online
USER_HOST: user-"{{ env }}.techdaws.online
CART_HOST: cart-"{{ env }}.techdaws.online
MYSQL_HOST: mysql-"{{ env }}.techdaws.online
# MYSQL_ROOT_PASSWORD: RoboShop@1
SHIPPING_HOST: shipping-"{{ env }}.techdaws.online
RABBITMQ_HOST: rabbitmq-"{{ env }}.techdaws.online
PAYMENT_HOST: payment-"{{ env }}.techdaws.online
