[mongodb]
mongodb-dev.techdaws.online

[catalogue]
catalogue-dev.techdaws.online

[redis]
redis-dev.techdaws.online

[user]
user-dev.techdaws.online

[cart]
cart-dev.techdaws.online

[mysql]
mysql-dev.techdaws.online

[shipping]
shipping-dev.techdaws.online

[rabbitmq]
rabbitmq-dev.techdaws.online

[payment]
payment-dev.techdaws.online

[frontend]
frontend-dev.techdaws.online

[all:vars]
ansible_user=ec2-user
ansible_password= DevOps321